Initial Commit
mlukso/javascript-workbook pull request #1
Opened 2018-07-18 03:59 UTC by mlukso

## Checkpoint Rubric
This is the rubric that your instructor will use to grade your checkpoints. Please do not edit. 

**Checkpoint 1**
- [ ] All tests passed: 40 points
- [ ] Proper use of documentation (commenting on code): 15 points
- [ ] Properly indented code: 15 points
- [ ] Demonstrated effective use of JavaScript: 30 points

**Checkpoint 2**
- [ ] The application works as it should: 40 points
- [ ] Proper use of documentation (commenting on code): 15 points
- [ ] Properly indented code: 15 points
- [ ] Demonstrated effective use of JavaScript and the DOM API: 30 points

**Checkpoint 3**
- [ ] Use of React: 25 points
- [ ] Accesses an API: 25 points
- [ ] Proper use of documentation (commenting on code): 25 points
- [ ] The application functions as it should: 25 points

2018-07-22 22:12 UTC, reneemeyer requested changes
Nice job, please address comments above.

2018-07-22 22:12 UTC, reneedudley commented on 01week/datatypes.js
> +const currentTime = Date();
This is a variable, I need a function.

2018-07-22 22:12 UTC, reneedudley commented on 01week/datatypes.js
> +const numberToString = String(value2)
This is a variable that stores '100'. I need a function to turn any number into a string and return that string.

2018-07-22 22:12 UTC, reneedudley commented on 01week/datatypes.js
> +const stringToNumber =  Number(value1);
This is a variable that stores 10. I need a function that converts ANY string into a number and converts it.

2018-07-22 22:12 UTC, reneedudley commented on 01week/datatypes.js
> +const input = "test"
This is a  variable. I need a function that accepts ANY argument and returns it's data type

2018-07-25 06:15 UTC, mlukso commented
@reneedudley I've revised the code per your suggestions! https://github.com/mlukso/javascript-workbook/pull/1/commits/bdc935f25a7f416bffcea9aeed650ff5866a6910

I'll send you an email as well. Thanks!

2018-07-30 22:16 UTC, reneemeyer reviewed
Nice job, see comments below, address changes then merge

2018-07-30 22:16 UTC, reneedudley commented on 01week/datatypes.js
> +const numberToString=(value1)=>{return String(value1)}
This is a one line function so the curly brackets and return are unnecessary. 
```javascript
const currentTime=()=> Date()
```

2018-07-30 22:16 UTC, reneedudley commented on 01week/datatypes.js
> +const stringToNumber=(value2)=>{return Number(value2)}
Same as the first problem.

2018-07-30 22:16 UTC, reneedudley commented on 01week/datatypes.js
> +const checkType=(value3)=>{return typeof value3}
same as the first problem

2018-07-30 22:16 UTC, reneedudley commented on 01week/datatypes.js
> +const sum=(num1, num2)=>{return Number(num1) + Number(num2)}
same as the first problem

2018-08-27 15:28 UTC, merged